import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { homedir } from "os";
import { WORKBENCH_DIR } from "#lib/config";

export type PackageManager = "yarn" | "npm" | "pnpm" | "bun";

export interface DependencyLinkManifest {
  sourceRepoDir: string;
  links: string[];
}

export const DEPS_MANIFEST_BASENAME = ".workbench-deps-manifest.sh";

const LOCKFILE_MAP: Record<string, PackageManager> = {
  "yarn.lock": "yarn",
  "pnpm-lock.yaml": "pnpm",
  "bun.lockb": "bun",
  "bun.lock": "bun",
  "package-lock.json": "npm",
};

const LOCKFILES_TO_COMPARE = [
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
  "package-lock.json",
  "npm-shrinkwrap.json",
] as const;

const EMPTY_MANAGED_LINKS = "typeset -ga WORKBENCH_MANAGED_DEP_LINKS=()";

/**
 * Detect which package manager a repo uses by checking for lockfiles.
 * Returns null if no known lockfile is found.
 */
export function detectPackageManager(repoDir: string): PackageManager | null {
  for (const [lockfile, pm] of Object.entries(LOCKFILE_MAP)) {
    if (existsSync(resolve(repoDir, lockfile))) {
      return pm;
    }
  }
  return null;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function runGit(args: string[], cwd: string): string[] {
  const result = Bun.spawnSync(["git", "-C", cwd, ...args], { stderr: "ignore", stdout: "pipe" });
  if (result.exitCode !== 0) {
    return [];
  }
  return result.stdout
    .toString()
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
}

function listTrackedPackageManifests(repoDir: string): string[] {
  return runGit(["ls-files", "--cached", "--full-name"], repoDir)
    .filter((file) => file === "package.json" || file.endsWith("/package.json"))
    .sort();
}

function getGitInfoExcludeFile(worktreeDir: string): string | null {
  const result = Bun.spawnSync(
    ["git", "-C", worktreeDir, "rev-parse", "--git-path", "info/exclude"],
    {
      stderr: "ignore",
      stdout: "pipe",
    },
  );
  if (result.exitCode !== 0) {
    return null;
  }

  const excludeFile = result.stdout.toString().trim();
  return excludeFile || null;
}

function addWorktreeExcludes(worktreeDir: string, entries: string[]): void {
  const excludeFile = getGitInfoExcludeFile(worktreeDir);
  if (!excludeFile) {
    return;
  }

  try {
    const existing = existsSync(excludeFile) ? readFileSync(excludeFile, "utf-8") : "";
    const missing = entries.filter((entry) => !existing.includes(entry));
    if (missing.length > 0) {
      appendFileSync(excludeFile, `\n${missing.join("\n")}\n`);
    }
  } catch {
    // Ignore exclude file failures; the linked files remain untracked.
  }
}

export function getDependencyLinksManifestPath(worktreeDir: string): string {
  return resolve(worktreeDir, DEPS_MANIFEST_BASENAME);
}

export function discoverDependencyLinks(sourceRepoDir: string): string[] {
  const links = new Set<string>();
  const rootNodeModules = resolve(sourceRepoDir, "node_modules");
  if (existsSync(rootNodeModules)) {
    links.add("node_modules");
  }

  for (const manifestPath of listTrackedPackageManifests(sourceRepoDir)) {
    const manifestDir = dirname(manifestPath);
    if (manifestDir === ".") {
      continue;
    }

    const linkPath = `${manifestDir}/node_modules`;
    if (existsSync(resolve(sourceRepoDir, linkPath))) {
      links.add(linkPath);
    }
  }

  return [...links].sort();
}

export function writeDependencyLinksManifest(
  worktreeDir: string,
  sourceRepoDir: string,
): DependencyLinkManifest {
  const manifest: DependencyLinkManifest = {
    sourceRepoDir,
    links: discoverDependencyLinks(sourceRepoDir),
  };

  const manifestFile = getDependencyLinksManifestPath(worktreeDir);
  const lines = [
    "# Auto-generated by workbench — managed dependency links for this worktree",
    `WORKBENCH_SOURCE_REPO=${shellQuote(sourceRepoDir)}`,
    manifest.links.length > 0
      ? `typeset -ga WORKBENCH_MANAGED_DEP_LINKS=(${manifest.links.map(shellQuote).join(" ")})`
      : EMPTY_MANAGED_LINKS,
    "",
  ];

  writeFileSync(manifestFile, lines.join("\n"));
  addWorktreeExcludes(worktreeDir, [DEPS_MANIFEST_BASENAME]);
  return manifest;
}

/**
 * Write a shell init script into the worktree that wraps package manager
 * commands to short-circuit unchanged installs and remove only managed
 * dependency links when they would be invalidated.
 * This file is sourced by the agent wrapper and can be sourced by
 * any other shell opened in the worktree.
 */
export function writeShellInit(worktreeDir: string, pm: PackageManager): void {
  const initFile = resolve(worktreeDir, ".workbench-shell-init.sh");

  // All package managers that could mutate node_modules need wrapping.
  // We wrap the detected one plus npm (always present as fallback).
  const pmsToWrap = new Set<string>([pm, "npm", "yarn", "pnpm", "bun"]);

  const shellHelpers = `WORKBENCH_DEPS_MANIFEST_BASENAME=${shellQuote(DEPS_MANIFEST_BASENAME)}
WORKBENCH_LOCKFILES=(${LOCKFILES_TO_COMPARE.map(shellQuote).join(" ")})
WORKBENCH_SOURCE_REPO="\${WORKBENCH_SOURCE_REPO:-}"
${EMPTY_MANAGED_LINKS}

workbench_worktree_root() {
    printf '%s\\n' "\${WORKTREE_DIR:-$PWD}"
}

workbench_deps_manifest_file() {
    printf '%s/%s\\n' "$(workbench_worktree_root)" "$WORKBENCH_DEPS_MANIFEST_BASENAME"
}

if [[ -f "$(workbench_deps_manifest_file)" ]]; then
    source "$(workbench_deps_manifest_file)"
fi

workbench_filter_package_manifests() {
    while IFS= read -r file; do
        if [[ "$file" == "package.json" || "$file" == */package.json ]]; then
            printf '%s\\n' "$file"
        fi
    done
}

workbench_list_tracked_package_manifests() {
    local root="$1"

    [[ -d "$root" ]] || return 1

    git -C "$root" ls-files --cached --full-name 2>/dev/null |
        workbench_filter_package_manifests |
        LC_ALL=C sort
}

workbench_list_worktree_package_manifests() {
    local root="$1"

    [[ -d "$root" ]] || return 1

    {
        git -C "$root" ls-files --cached --full-name 2>/dev/null
        git -C "$root" ls-files --others --exclude-standard --full-name 2>/dev/null
    } |
        workbench_filter_package_manifests |
        LC_ALL=C sort -u
}

workbench_dependency_inputs_differ() {
    local source_root="$WORKBENCH_SOURCE_REPO"
    local worktree_root="$(workbench_worktree_root)"
    local source_manifests
    local worktree_manifests
    local rel
    local lockfile
    local source_file
    local worktree_file

    [[ -n "$source_root" ]] || return 0

    source_manifests="$(workbench_list_tracked_package_manifests "$source_root")" || return 0
    worktree_manifests="$(workbench_list_worktree_package_manifests "$worktree_root")" || return 0

    if [[ "$source_manifests" != "$worktree_manifests" ]]; then
        return 0
    fi

    while IFS= read -r rel; do
        [[ -z "$rel" ]] && continue
        source_file="$source_root/$rel"
        worktree_file="$worktree_root/$rel"

        if [[ ! -e "$source_file" || ! -e "$worktree_file" ]]; then
            return 0
        fi

        if ! cmp -s "$source_file" "$worktree_file"; then
            return 0
        fi
    done <<< "$source_manifests"

    for lockfile in "\${WORKBENCH_LOCKFILES[@]}"; do
        source_file="$source_root/$lockfile"
        worktree_file="$worktree_root/$lockfile"

        if [[ ! -e "$source_file" && ! -e "$worktree_file" ]]; then
            continue
        fi

        if [[ ! -e "$source_file" || ! -e "$worktree_file" ]]; then
            return 0
        fi

        if ! cmp -s "$source_file" "$worktree_file"; then
            return 0
        fi
    done

    return 1
}

workbench_link_source_path() {
    local rel="$1"

    printf '%s/%s\\n' "$WORKBENCH_SOURCE_REPO" "$rel"
}

workbench_link_target_path() {
    local rel="$1"

    printf '%s/%s\\n' "$(workbench_worktree_root)" "$rel"
}

workbench_has_managed_links() {
    [[ -n "$WORKBENCH_SOURCE_REPO" ]] || return 1
    (( \${#WORKBENCH_MANAGED_DEP_LINKS[@]} > 0 ))
}

workbench_ensure_dependency_links() {
    local rel
    local source
    local target
    local target_parent

    workbench_has_managed_links || return 1

    for rel in "\${WORKBENCH_MANAGED_DEP_LINKS[@]}"; do
        source="$(workbench_link_source_path "$rel")"
        target="$(workbench_link_target_path "$rel")"
        target_parent="$(dirname "$target")"

        [[ -e "$source" ]] || continue
        if [[ -e "$target" || -L "$target" ]]; then
            continue
        fi

        mkdir -p "$target_parent"
        ln -s "$source" "$target"
        echo -e "\\033[2m   linked \${rel}\\033[0m"
    done

    return 0
}

workbench_managed_links_valid() {
    local rel
    local source
    local target

    workbench_has_managed_links || return 1

    for rel in "\${WORKBENCH_MANAGED_DEP_LINKS[@]}"; do
        source="$(workbench_link_source_path "$rel")"
        target="$(workbench_link_target_path "$rel")"

        [[ -e "$source" ]] || return 1
        [[ -L "$target" ]] || return 1
        [[ "$(readlink "$target")" == "$source" ]] || return 1
    done

    return 0
}

workbench_remove_dependency_links() {
    local rel
    local target

    workbench_has_managed_links || return 1

    for rel in "\${WORKBENCH_MANAGED_DEP_LINKS[@]}"; do
        target="$(workbench_link_target_path "$rel")"
        if [[ -L "$target" ]]; then
            echo -e "\\033[2m   removing linked \${rel}...\\033[0m"
            rm "$target"
        fi
    done

    return 0
}

workbench_skip_install_if_unchanged() {
    local name="$1"

    shift
    workbench_has_managed_links || return 1

    if workbench_dependency_inputs_differ; then
        return 1
    fi

    workbench_ensure_dependency_links >/dev/null
    if ! workbench_managed_links_valid; then
        return 1
    fi

    echo -e "\\033[2m   skipping \${name} install; dependencies unchanged\\033[0m"
    return 0
}

workbench_has_positional_arg() {
    local arg

    for arg in "$@"; do
        if [[ "$arg" == "--" || "$arg" != -* ]]; then
            return 0
        fi
    done

    return 1
}

workbench_is_install_like_yarn() {
    local cmd="\${1:-install}"

    if [[ $# -eq 0 || "$cmd" == -* ]]; then
        return 0
    fi

    case "$cmd" in
        install|i)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

workbench_should_skip_yarn() {
    workbench_is_install_like_yarn "$@" || return 1
    workbench_skip_install_if_unchanged yarn "$@"
}

workbench_should_unlink_yarn() {
    local cmd="\${1:-install}"

    if [[ $# -gt 0 ]]; then
        shift
    fi

    case "$cmd" in
        add|remove|up|upgrade|upgrade-interactive|dedupe|import)
            return 0
            ;;
        install|i)
            workbench_dependency_inputs_differ
            return $?
            ;;
        *)
            if [[ "$cmd" == -* ]]; then
                workbench_dependency_inputs_differ
                return $?
            fi
            return 1
            ;;
    esac
}

workbench_should_skip_npm() {
    local cmd="\${1:-}"

    if [[ $# -gt 0 ]]; then
        shift
    fi

    case "$cmd" in
        install|i)
            if workbench_has_positional_arg "$@"; then
                return 1
            fi
            workbench_skip_install_if_unchanged npm
            return $?
            ;;
        *)
            return 1
            ;;
    esac
}

workbench_should_unlink_npm() {
    local cmd="\${1:-}"

    if [[ $# -gt 0 ]]; then
        shift
    fi

    case "$cmd" in
        add|uninstall|remove|rm|update|upgrade|dedupe|prune|ci)
            return 0
            ;;
        install|i)
            if workbench_has_positional_arg "$@"; then
                return 0
            fi

            workbench_dependency_inputs_differ
            return $?
            ;;
        *)
            return 1
            ;;
    esac
}

workbench_should_skip_pnpm() {
    local cmd="\${1:-}"

    case "$cmd" in
        install|i)
            workbench_skip_install_if_unchanged pnpm
            return $?
            ;;
        *)
            return 1
            ;;
    esac
}

workbench_should_unlink_pnpm() {
    local cmd="\${1:-}"

    if [[ $# -gt 0 ]]; then
        shift
    fi

    case "$cmd" in
        add|remove|rm|update|up|upgrade|dedupe|prune|import)
            return 0
            ;;
        install|i)
            workbench_dependency_inputs_differ
            return $?
            ;;
        *)
            return 1
            ;;
    esac
}

workbench_should_skip_bun() {
    local cmd="\${1:-}"

    case "$cmd" in
        install|i)
            workbench_skip_install_if_unchanged bun
            return $?
            ;;
        *)
            return 1
            ;;
    esac
}

workbench_should_unlink_bun() {
    local cmd="\${1:-}"

    if [[ $# -gt 0 ]]; then
        shift
    fi

    case "$cmd" in
        add|remove|rm|update|up)
            return 0
            ;;
        install|i)
            workbench_dependency_inputs_differ
            return $?
            ;;
        *)
            return 1
            ;;
    esac
}

workbench_ensure_dependency_links >/dev/null 2>&1 || true
`;

  const wrappers = [...pmsToWrap]
    .map(
      (name) => `${name}() {
    if workbench_should_skip_${name} "$@"; then
        return 0
    fi
    if workbench_should_unlink_${name} "$@"; then
        workbench_remove_dependency_links >/dev/null
    fi
    command ${name} "$@"
}`,
    )
    .join("\n\n");

  writeFileSync(
    initFile,
    `# Auto-generated by workbench — manages shared dependency links for this worktree
${shellHelpers}

${wrappers}
`,
  );

  addWorktreeExcludes(worktreeDir, [".workbench-shell-init.sh"]);
}

const SHELL_HOOK_FILE = resolve(WORKBENCH_DIR, "shell-init.zsh");
const SHELL_HOOK_CONTENT = `# workbench: conditionally source worktree shell init when entering a directory
# Only activates if the directory has a .workbench-shell-init.sh (created by workbench spawn).
# In all other directories, yarn/bun/npm/pnpm remain completely untouched.
_workbench_chpwd() {
    [[ -f "$PWD/.workbench-shell-init.sh" ]] && source "$PWD/.workbench-shell-init.sh"
}
autoload -Uz add-zsh-hook
add-zsh-hook chpwd _workbench_chpwd
_workbench_chpwd  # run on shell startup for initial directory
`;

const ZSHRC_SOURCE_LINE = `source "${SHELL_HOOK_FILE}"`;

/**
 * Ensure the global zsh chpwd hook file exists. Returns whether
 * ~/.zshrc still needs the source line added.
 */
export function ensureShellHook(): { installed: boolean; needsSetup: boolean } {
  mkdirSync(WORKBENCH_DIR, { recursive: true });

  // Always write/update the hook file
  writeFileSync(SHELL_HOOK_FILE, SHELL_HOOK_CONTENT);

  // Check if ~/.zshrc sources it
  const zshrc = resolve(homedir(), ".zshrc");
  try {
    const content = existsSync(zshrc) ? readFileSync(zshrc, "utf-8") : "";
    if (content.includes("shell-init.zsh")) {
      return { installed: true, needsSetup: false };
    }
  } catch {
    // Can't read .zshrc
  }

  return { installed: true, needsSetup: true };
}

/**
 * Append the source line to ~/.zshrc so the chpwd hook is loaded in all shells.
 */
export function installShellHook(): void {
  const zshrc = resolve(homedir(), ".zshrc");
  appendFileSync(
    zshrc,
    `\n# workbench: auto-source worktree shell wrappers on cd\n${ZSHRC_SOURCE_LINE}\n`,
  );
}
